<a href="https://colab.research.google.com/github/AnzhelikaKodlubovska/First_repo/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# 1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2
matrix_1 = np.zeros((3, 3), dtype="u4")
print(matrix_1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# 3
matrix_2 = np.random.randint(1, 11, size=(5, 5))
print(matrix_2)

[[10  2  2  9  8]
 [10  3  6  4 10]
 [ 2  7  6  1  8]
 [ 1  4  9  1  8]
 [ 9  3  8  9  8]]


In [14]:
# 4
matrix_3 = np.random.randint(0, 2, size=(4, 4))
print(matrix_3)

[[0 0 0 0]
 [0 0 1 0]
 [1 1 0 0]
 [0 1 0 1]]


In [19]:
# 5
a = np.random.randint(1, 11, size=(5))
b = np.random.randint(1, 11, size=(5))

print(a)
print(b)
print(f'Додавання: {a + b}')
print(f'Віднімання: {a - b}')
print(f'Множення: {a * b}')


[5 8 2 1 2]
[8 2 2 3 2]
Додавання: [13 10  4  4  4]
Віднімання: [-3  6  0 -2  0]
Множення: [40 16  4  3  4]


In [22]:
# 6
a = np.random.random(7)
b = np.random.random(7)

print(a)
print(b)
print(np.dot(a, b))

[0.55864865 0.57275209 0.55460033 0.83243175 0.21980494 0.07115056
 0.60895963]
[0.64199776 0.10887194 0.97757926 0.13798545 0.44823983 0.89621772
 0.10597121]
1.3048609806354585


In [26]:
# 7
matrix_a = np.random.randint(1, 11, size=(2, 2))
matrix_b = np.random.randint(1, 11, size=(2, 3))

print(np.dot(matrix_a, matrix_b))

[[21 19 22]
 [48 47 50]]


In [32]:
# 8
matrix_4 = np.random.randint(1, 11, size=(3, 3))

print(matrix_4)
print(np.linalg.inv(matrix_4))

[[2 1 2]
 [8 9 3]
 [7 6 9]]
[[ 1.4         0.06666667 -0.33333333]
 [-1.13333333  0.08888889  0.22222222]
 [-0.33333333 -0.11111111  0.22222222]]


In [35]:
# 9
matrix_5 = np.random.randint(0, 2, size=(4, 4))

print(matrix_5)
print(' ')
print(matrix_5.T)

[[1 0 0 0]
 [0 1 1 0]
 [1 1 0 1]
 [0 0 1 0]]
 
[[1 0 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 0]]


In [37]:
# 10
matrix_c = np.random.randint(1, 11, size=(3, 4))
c = np.random.randint(1, 11, size=(4))

print(matrix_c)
print(' ')
print(c)
print(' ')
print(np.dot(matrix_c, c))

[[2 7 8 2]
 [2 3 3 2]
 [6 2 1 4]]
 
[7 6 2 5]
 
[82 48 76]


In [38]:
# 11
matrix_d = np.random.randint(0, 2, size=(2, 3))
d = np.random.randint(0, 2, size=(3))

print(matrix_d)
print(' ')
print(d)
print(' ')
print(np.dot(matrix_d, d))

[[1 0 0]
 [1 1 1]]
 
[0 0 0]
 
[0 0]


In [41]:
# 12
matrix_f = np.random.randint(1, 11, size=(2, 2))
matrix_j = np.random.randint(1, 11, size=(2, 2))

print(matrix_f)
print(' ')
print(matrix_j)
print(' ')
print(matrix_f * matrix_j)

[[6 7]
 [2 2]]
 
[[2 2]
 [3 2]]
 
[[12 14]
 [ 6  4]]


In [42]:
# 13
matrix_s = np.random.randint(1, 11, size=(2, 2))
matrix_z = np.random.randint(1, 11, size=(2, 2))

print(matrix_s)
print(' ')
print(matrix_z)
print(' ')
print(np.matmul(matrix_f,matrix_j))

[[ 1 10]
 [ 8  1]]
 
[[2 5]
 [1 6]]
 
[[33 26]
 [10  8]]


In [44]:
# 14
matrix_6 = np.random.randint(1, 101, size=(5, 5))

print(matrix_6)
print(' ')
print(sum(matrix_z))

[[18 60 55 81  4]
 [41 96  3 43 47]
 [95 77 99 40 15]
 [54 52 85 27 72]
 [72 92 69 86 32]]
 
[ 3 11]


In [45]:
# 15
matrix_7 = np.random.randint(1, 11, size=(4, 4))
matrix_8 = np.random.randint(1, 11, size=(4, 4))

print(matrix_7)
print(' ')
print(matrix_8)
print(' ')
print(matrix_7 - matrix_8)

[[ 2  9  1 10]
 [ 7  6  5  9]
 [ 1  3  8  7]
 [ 8 10  2  3]]
 
[[7 9 3 9]
 [3 8 3 9]
 [5 3 3 5]
 [7 4 1 2]]
 
[[-5  0 -2  1]
 [ 4 -2  2  0]
 [-4  0  5  2]
 [ 1  6  1  1]]


In [61]:
# 16
matrix_9 = np.random.randint(0, 2, size=(3, 3))

print(matrix_9)
print(' ')
print(np.sum(matrix_9, axis=1))


[[1 0 1]
 [0 1 1]
 [1 1 1]]
 
[2 2 3]


In [69]:
# 17
matrix_o = np.random.random(size=(3, 4))

print(matrix_o)
print(' ')
print(matrix_o**2)

[[0.55867618 0.46097084 0.63028867 0.76680131]
 [0.74866883 0.09143766 0.99871307 0.92068059]
 [0.68325759 0.25091607 0.67499495 0.8270165 ]]
 
[[0.31211908 0.21249411 0.39726381 0.58798425]
 [0.56050501 0.00836085 0.99742779 0.84765275]
 [0.46684093 0.06295887 0.45561819 0.6839563 ]]


In [72]:
# 18
f = np.random.randint(1, 51, size=(4))

print(f)
print(' ')
print(np.sqrt(f))


[42  4 26 38]
 
[6.4807407  2.         5.09901951 6.164414  ]
