<a href="https://colab.research.google.com/github/AnzhelikaKodlubovska/First_repo/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

# a = np.array([1, 2, 3, 4, 5], dtype=float)
# b = 5*a

# a = np.array([1, 2, 3])
# b = np.array([1, 2, 3])

# print(a + b)
# print(a - b)
# print(np.dot(a, b))
# print(f'{b}, size a: {a.size}')

# matrix_1 = np.array([[1, 2, 3], [2, 4, 6]], dtype = int)
# print(matrix_1.shape)


# a = np.array([[1, 2, 3],
#               [0, 1, 2]])

# b = np.array([[ 1, 2],
#               [ 0, 4],
#               [-1, 0]])

# c = np.dot(a, b)
# print(c)

import numpy as np

a = np.eye(4, k=0, dtype=float)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
